-- Wanderlust - class trainer coordinates
local WL = Wanderlust

WL.ClassTrainers = {
    ["Danlaar Nightstride"] = { zone = "Ashenvale", x = 50.00, y = 67.80, faction = "Alliance", class = "Hunter" },
    ["Anishar"] = { zone = "Darnassus", x = 37.80, y = 21.40, faction = "Alliance", class = "Rogue" },
    ["Arias'ta Bladesinger"] = { zone = "Darnassus", x = 58.40, y = 35.20, faction = "Alliance", class = "Warrior" },
    ["Astarii Starseeker"] = { zone = "Darnassus", x = 38.40, y = 80.80, faction = "Alliance", class = "Priest" },
    ["Darnath Bladesinger"] = { zone = "Darnassus", x = 58.60, y = 35.60, faction = "Alliance", class = "Warrior" },
    ["Denatharion"] = { zone = "Darnassus", x = 34.80, y = 7.80, faction = "Alliance", class = "Druid" },
    ["Dorion"] = { zone = "Darnassus", x = 42.20, y = 7.60, faction = "Alliance", class = "Hunter" },
    ["Elissa Dumas"] = { zone = "Darnassus", x = 40.40, y = 82.00, faction = "Alliance", class = "Mage" },
    ["Erion Shadewhisper"] = { zone = "Darnassus", x = 34.60, y = 25.60, faction = "Alliance", class = "Rogue" },
    ["Fylerian Nightwing"] = { zone = "Darnassus", x = 33.60, y = 8.60, faction = "Alliance", class = "Druid" },
    ["Jandria"] = { zone = "Darnassus", x = 38.00, y = 82.60, faction = "Alliance", class = "Priest" },
    ["Jeen'ra Nightrunner"] = { zone = "Darnassus", x = 39.60, y = 5.80, faction = "Alliance", class = "Hunter" },
    ["Jocaste"] = { zone = "Darnassus", x = 40.20, y = 8.80, faction = "Alliance", class = "Hunter" },
    ["Lariia"] = { zone = "Darnassus", x = 40.00, y = 87.40, faction = "Alliance", class = "Priest" },
    ["Mathrengyl Bearwalker"] = { zone = "Darnassus", x = 35.20, y = 8.00, faction = "Alliance", class = "Druid" },
    ["Priestess Alathea"] = { zone = "Darnassus", x = 39.20, y = 81.00, faction = "Alliance", class = "Priest" },
    ["Sildanair"] = { zone = "Darnassus", x = 61.80, y = 41.80, faction = "Alliance", class = "Warrior" },
    ["Syurna"] = { zone = "Darnassus", x = 36.80, y = 21.80, faction = "Alliance", class = "Rogue" },
    ["Alamar Grimm"] = { zone = "Dun Morogh", x = 28.60, y = 66.20, faction = "Alliance", class = "Warlock" },
    ["Azar Stronghammer"] = { zone = "Dun Morogh", x = 47.60, y = 52.00, faction = "Alliance", class = "Paladin" },
    ["Branstock Khalder"] = { zone = "Dun Morogh", x = 28.60, y = 66.40, faction = "Alliance", class = "Priest" },
    ["Bromos Grummner"] = { zone = "Dun Morogh", x = 28.80, y = 68.20, faction = "Alliance", class = "Paladin" },
    ["Dannie Fizzwizzle"] = { zone = "Dun Morogh", x = 47.20, y = 53.65, faction = "Alliance", class = "Warlock" },
    ["Gimrizz Shadowcog"] = { zone = "Dun Morogh", x = 47.20, y = 53.60, faction = "Alliance", class = "Warlock" },
    ["Granis Swiftaxe"] = { zone = "Dun Morogh", x = 47.20, y = 52.60, faction = "Alliance", class = "Warrior" },
    ["Grif Wildheart"] = { zone = "Dun Morogh", x = 45.80, y = 53.00, faction = "Alliance", class = "Hunter" },
    ["Hogral Bakkan"] = { zone = "Dun Morogh", x = 47.60, y = 52.60, faction = "Alliance", class = "Rogue" },
    ["Magis Sparkmantle"] = { zone = "Dun Morogh", x = 47.40, y = 52.00, faction = "Alliance", class = "Mage" },
    ["Marryk Nurribit"] = { zone = "Dun Morogh", x = 28.60, y = 66.45, faction = "Alliance", class = "Mage" },
    ["Maxan Anvol"] = { zone = "Dun Morogh", x = 47.20, y = 52.20, faction = "Alliance", class = "Priest" },
    ["Solm Hargrin"] = { zone = "Dun Morogh", x = 28.40, y = 67.40, faction = "Alliance", class = "Rogue" },
    ["Thorgas Grimson"] = { zone = "Dun Morogh", x = 29.00, y = 67.40, faction = "Alliance", class = "Hunter" },
    ["Thran Khorman"] = { zone = "Dun Morogh", x = 28.80, y = 67.20, faction = "Alliance", class = "Warrior" },
    ["Wren Darkspring"] = { zone = "Dun Morogh", x = 28.80, y = 66.20, faction = "Alliance", class = "Warlock" },
    ["Brother Karman"] = { zone = "Dustwallow Marsh", x = 67.40, y = 47.40, faction = "Alliance", class = "Paladin" },
    ["Captain Evencane"] = { zone = "Dustwallow Marsh", x = 67.80, y = 48.40, faction = "Alliance", class = "Warrior" },
    ["Brother Sammuel"] = { zone = "Elwynn Forest", x = 50.40, y = 42.00, faction = "Alliance", class = "Paladin" },
    ["Brother Wilhelm"] = { zone = "Elwynn Forest", x = 41.00, y = 66.00, faction = "Alliance", class = "Paladin" },
    ["Cylina Darkheart"] = { zone = "Elwynn Forest", x = 44.40, y = 66.00, faction = "Alliance", class = "Warlock" },
    ["Dane Winslow"] = { zone = "Elwynn Forest", x = 50.00, y = 42.60, faction = "Alliance", class = "Warlock" },
    ["Drusilla La Salle"] = { zone = "Elwynn Forest", x = 49.80, y = 42.60, faction = "Alliance", class = "Warlock" },
    ["Jorik Kerridan"] = { zone = "Elwynn Forest", x = 50.40, y = 39.80, faction = "Alliance", class = "Rogue" },
    ["Khelden Bremen"] = { zone = "Elwynn Forest", x = 49.60, y = 39.40, faction = "Alliance", class = "Mage" },
    ["Llane Beshere"] = { zone = "Elwynn Forest", x = 50.20, y = 42.20, faction = "Alliance", class = "Warrior" },
    ["Lyria Du Lac"] = { zone = "Elwynn Forest", x = 41.00, y = 65.80, faction = "Alliance", class = "Warrior" },
    ["Maximillian Crowe"] = { zone = "Elwynn Forest", x = 44.40, y = 66.20, faction = "Alliance", class = "Warlock" },
    ["Priestess Anetta"] = { zone = "Elwynn Forest", x = 49.80, y = 39.60, faction = "Alliance", class = "Priest" },
    ["Priestess Josetta"] = { zone = "Elwynn Forest", x = 43.40, y = 65.60, faction = "Alliance", class = "Priest" },
    ["Zaldimar Wefhellt"] = { zone = "Elwynn Forest", x = 43.20, y = 66.20, faction = "Alliance", class = "Mage" },
    ["Golhine the Hooded"] = { zone = "Felwood", x = 62.00, y = 24.40, faction = "Alliance", class = "Druid" },
    ["Kaerbrus"] = { zone = "Felwood", x = 61.80, y = 23.60, faction = "Alliance", class = "Hunter" },
    ["Alexander Calder"] = { zone = "Ironforge", x = 50.20, y = 7.00, faction = "Alliance", class = "Warlock" },
    ["Beldruk Doombrow"] = { zone = "Ironforge", x = 24.60, y = 4.80, faction = "Alliance", class = "Paladin" },
    ["Bilban Tosslespanner"] = { zone = "Ironforge", x = 66.20, y = 88.20, faction = "Alliance", class = "Warrior" },
    ["Bink"] = { zone = "Ironforge", x = 27.00, y = 8.20, faction = "Alliance", class = "Mage" },
    ["Braenna Flintcrag"] = { zone = "Ironforge", x = 24.60, y = 9.20, faction = "Alliance", class = "Priest" },
    ["Brandur Ironhammer"] = { zone = "Ironforge", x = 23.40, y = 6.40, faction = "Alliance", class = "Paladin" },
    ["Briarthorn"] = { zone = "Ironforge", x = 50.20, y = 6.00, faction = "Alliance", class = "Warlock" },
    ["Daera Brightspear"] = { zone = "Ironforge", x = 71.00, y = 90.00, faction = "Alliance", class = "Hunter" },
    ["Dink"] = { zone = "Ironforge", x = 26.80, y = 8.40, faction = "Alliance", class = "Mage" },
    ["Fenthwick"] = { zone = "Ironforge", x = 51.60, y = 15.00, faction = "Alliance", class = "Rogue" },
    ["High Priest Rohan"] = { zone = "Ironforge", x = 25.00, y = 8.40, faction = "Alliance", class = "Priest" },
    ["Hulfdan Blackbeard"] = { zone = "Ironforge", x = 51.60, y = 14.60, faction = "Alliance", class = "Rogue" },
    ["Jubahl Corpseseeker"] = { zone = "Ironforge", x = 53.00, y = 6.20, faction = "Alliance", class = "Warlock" },
    ["Juli Stormkettle"] = { zone = "Ironforge", x = 26.20, y = 7.20, faction = "Alliance", class = "Mage" },
    ["Kelstrum Stonebreaker"] = { zone = "Ironforge", x = 67.00, y = 89.60, faction = "Alliance", class = "Warrior" },
    ["Kelv Sternhammer"] = { zone = "Ironforge", x = 70.20, y = 90.60, faction = "Alliance", class = "Warrior" },
    ["Milstaff Stormeye"] = { zone = "Ironforge", x = 25.60, y = 7.40, faction = "Alliance", class = "Mage" },
    ["Nittlebur Sparkfizzle"] = { zone = "Ironforge", x = 26.00, y = 6.00, faction = "Alliance", class = "Mage" },
    ["Olmin Burningbeard"] = { zone = "Ironforge", x = 70.60, y = 83.80, faction = "Alliance", class = "Hunter" },
    ["Ormyr Flinteye"] = { zone = "Ironforge", x = 52.40, y = 15.00, faction = "Alliance", class = "Rogue" },
    ["Regnus Thundergranite"] = { zone = "Ironforge", x = 69.80, y = 83.40, faction = "Alliance", class = "Hunter" },
    ["Theodrus Frostbeard"] = { zone = "Ironforge", x = 23.80, y = 8.80, faction = "Alliance", class = "Priest" },
    ["Thistleheart"] = { zone = "Ironforge", x = 50.80, y = 6.60, faction = "Alliance", class = "Warlock" },
    ["Toldren Deepiron"] = { zone = "Ironforge", x = 25.20, y = 10.20, faction = "Alliance", class = "Priest" },
    ["Valgar Highforge"] = { zone = "Ironforge", x = 23.40, y = 5.00, faction = "Alliance", class = "Paladin" },
    ["Dargh Trueaim"] = { zone = "Loch Modan", x = 82.20, y = 62.40, faction = "Alliance", class = "Hunter" },
    ["Ander Germaine"] = { zone = "Stormwind City", x = 78.20, y = 47.20, faction = "Alliance", class = "Warrior" },
    ["Arthur the Faithful"] = { zone = "Stormwind City", x = 38.60, y = 32.60, faction = "Alliance", class = "Paladin" },
    ["Brother Benjamin"] = { zone = "Stormwind City", x = 41.00, y = 28.20, faction = "Alliance", class = "Priest" },
    ["Brother Joshua"] = { zone = "Stormwind City", x = 38.80, y = 26.80, faction = "Alliance", class = "Priest" },
    ["Demisette Cloyce"] = { zone = "Stormwind City", x = 25.40, y = 78.20, faction = "Alliance", class = "Warlock" },
    ["Einris Brightspear"] = { zone = "Stormwind City", x = 61.60, y = 15.40, faction = "Alliance", class = "Hunter" },
    ["Elsharin"] = { zone = "Stormwind City", x = 37.00, y = 81.20, faction = "Alliance", class = "Mage" },
    ["High Priestess Laurena"] = { zone = "Stormwind City", x = 38.80, y = 26.40, faction = "Alliance", class = "Priest" },
    ["Ilsa Corbin"] = { zone = "Stormwind City", x = 78.60, y = 45.60, faction = "Alliance", class = "Warrior" },
    ["Jennea Cannon"] = { zone = "Stormwind City", x = 38.60, y = 79.40, faction = "Alliance", class = "Mage" },
    ["Katherine the Pure"] = { zone = "Stormwind City", x = 37.40, y = 32.00, faction = "Alliance", class = "Paladin" },
    ["Larimaine Purdue"] = { zone = "Stormwind City", x = 39.40, y = 79.60, faction = "Alliance", class = "Mage" },
    ["Lord Grayson Shadowbreaker"] = { zone = "Stormwind City", x = 37.20, y = 33.00, faction = "Alliance", class = "Paladin" },
    ["Lord Tony Romano"] = { zone = "Stormwind City", x = 78.20, y = 57.20, faction = "Alliance", class = "Rogue" },
    ["Maginor Dumas"] = { zone = "Stormwind City", x = 38.00, y = 81.60, faction = "Alliance", class = "Mage" },
    ["Maldryn"] = { zone = "Stormwind City", x = 19.00, y = 52.40, faction = "Alliance", class = "Druid" },
    ["Nara Meideros"] = { zone = "Stormwind City", x = 20.20, y = 50.80, faction = "Alliance", class = "Priest" },
    ["Osborne the Night Man"] = { zone = "Stormwind City", x = 74.40, y = 52.80, faction = "Alliance", class = "Rogue" },
    ["Sandahl"] = { zone = "Stormwind City", x = 25.80, y = 79.00, faction = "Alliance", class = "Warlock" },
    ["Sheldras Moontree"] = { zone = "Stormwind City", x = 21.00, y = 55.40, faction = "Alliance", class = "Druid" },
    ["Spackle Thornberry"] = { zone = "Stormwind City", x = 25.80, y = 77.60, faction = "Alliance", class = "Warlock" },
    ["Theridran"] = { zone = "Stormwind City", x = 21.40, y = 51.40, faction = "Alliance", class = "Druid" },
    ["Thorfin Stoneshield"] = { zone = "Stormwind City", x = 62.40, y = 14.60, faction = "Alliance", class = "Hunter" },
    ["Ulfir Ironbeard"] = { zone = "Stormwind City", x = 62.00, y = 15.00, faction = "Alliance", class = "Hunter" },
    ["Ursula Deline"] = { zone = "Stormwind City", x = 26.20, y = 77.40, faction = "Alliance", class = "Warlock" },
    ["Wu Shen"] = { zone = "Stormwind City", x = 78.80, y = 45.60, faction = "Alliance", class = "Warrior" },
    ["Alyissia"] = { zone = "Teldrassil", x = 59.60, y = 38.40, faction = "Alliance", class = "Warrior" },
    ["Ayanna Everstride"] = { zone = "Teldrassil", x = 58.60, y = 40.40, faction = "Alliance", class = "Hunter" },
    ["Dazalar"] = { zone = "Teldrassil", x = 56.60, y = 59.40, faction = "Alliance", class = "Hunter" },
    ["Frahun Shadewhisper"] = { zone = "Teldrassil", x = 59.60, y = 38.60, faction = "Alliance", class = "Rogue" },
    ["Jannok Breezesong"] = { zone = "Teldrassil", x = 56.20, y = 60.00, faction = "Alliance", class = "Rogue" },
    ["Kal"] = { zone = "Teldrassil", x = 56.00, y = 61.60, faction = "Alliance", class = "Druid" },
    ["Kyra Windblade"] = { zone = "Teldrassil", x = 56.20, y = 59.20, faction = "Alliance", class = "Warrior" },
    ["Laurna Morninglight"] = { zone = "Teldrassil", x = 55.60, y = 56.80, faction = "Alliance", class = "Priest" },
    ["Mardant Strongoak"] = { zone = "Teldrassil", x = 58.60, y = 40.45, faction = "Alliance", class = "Druid" },
    ["Shanda"] = { zone = "Teldrassil", x = 59.20, y = 40.40, faction = "Alliance", class = "Priest" },

    ["Dhugru Gorelust"] = { zone = "Durotar", x = 54.20, y = 41.20, faction = "Horde", class = "Warlock" },
    ["Frang"] = { zone = "Durotar", x = 42.80, y = 69.40, faction = "Horde", class = "Warrior" },
    ["Hraug"] = { zone = "Durotar", x = 40.60, y = 68.45, faction = "Horde", class = "Warlock" },
    ["Jen'shan"] = { zone = "Durotar", x = 42.80, y = 69.20, faction = "Horde", class = "Hunter" },
    ["Kaplak"] = { zone = "Durotar", x = 52.00, y = 43.60, faction = "Horde", class = "Rogue" },
    ["Ken'jai"] = { zone = "Durotar", x = 42.40, y = 68.80, faction = "Horde", class = "Priest" },
    ["Kitha"] = { zone = "Durotar", x = 54.60, y = 41.40, faction = "Horde", class = "Warlock" },
    ["Mai'ah"] = { zone = "Durotar", x = 42.40, y = 69.05, faction = "Horde", class = "Mage" },
    ["Nartok"] = { zone = "Durotar", x = 40.60, y = 68.40, faction = "Horde", class = "Warlock" },
    ["Rwag"] = { zone = "Durotar", x = 41.20, y = 68.00, faction = "Horde", class = "Rogue" },
    ["Shikrik"] = { zone = "Durotar", x = 42.40, y = 69.00, faction = "Horde", class = "Shaman" },
    ["Swart"] = { zone = "Durotar", x = 54.40, y = 42.60, faction = "Horde", class = "Shaman" },
    ["Tai'jin"] = { zone = "Durotar", x = 54.20, y = 42.80, faction = "Horde", class = "Priest" },
    ["Tarshaw Jaggedscar"] = { zone = "Durotar", x = 54.20, y = 42.40, faction = "Horde", class = "Warrior" },
    ["Thotar"] = { zone = "Durotar", x = 51.80, y = 43.40, faction = "Horde", class = "Hunter" },
    ["Un'Thuwa"] = { zone = "Durotar", x = 56.20, y = 75.00, faction = "Horde", class = "Mage" },
    ["Jannos Lighthoof"] = { zone = "Feralas", x = 76.00, y = 42.20, faction = "Horde", class = "Druid" },
    ["Gart Mistrunner"] = { zone = "Mulgore", x = 45.00, y = 76.00, faction = "Horde", class = "Druid" },
    ["Gennia Runetotem"] = { zone = "Mulgore", x = 48.40, y = 59.60, faction = "Horde", class = "Druid" },
    ["Harutt Thunderhorn"] = { zone = "Mulgore", x = 44.00, y = 76.00, faction = "Horde", class = "Warrior" },
    ["Krang Stonehoof"] = { zone = "Mulgore", x = 49.40, y = 60.40, faction = "Horde", class = "Warrior" },
    ["Lanka Farshot"] = { zone = "Mulgore", x = 44.20, y = 75.80, faction = "Horde", class = "Hunter" },
    ["Meela Dawnstrider"] = { zone = "Mulgore", x = 45.00, y = 76.05, faction = "Horde", class = "Shaman" },
    ["Narm Skychaser"] = { zone = "Mulgore", x = 48.40, y = 59.20, faction = "Horde", class = "Shaman" },
    ["Yaw Sharpmane"] = { zone = "Mulgore", x = 47.80, y = 55.60, faction = "Horde", class = "Hunter" },
    ["Deino"] = { zone = "Orgrimmar", x = 38.40, y = 85.80, faction = "Horde", class = "Mage" },
    ["Enyo"] = { zone = "Orgrimmar", x = 38.80, y = 85.40, faction = "Horde", class = "Mage" },
    ["Gest"] = { zone = "Orgrimmar", x = 42.80, y = 51.40, faction = "Horde", class = "Rogue" },
    ["Grezz Ragefist"] = { zone = "Orgrimmar", x = 79.60, y = 31.40, faction = "Horde", class = "Warrior" },
    ["Grol'dar"] = { zone = "Orgrimmar", x = 48.00, y = 46.20, faction = "Horde", class = "Warlock" },
    ["Kardris Dreamseeker"] = { zone = "Orgrimmar", x = 38.80, y = 36.60, faction = "Horde", class = "Shaman" },
    ["Kurgul"] = { zone = "Orgrimmar", x = 47.60, y = 46.80, faction = "Horde", class = "Warlock" },
    ["Mirket"] = { zone = "Orgrimmar", x = 48.40, y = 47.00, faction = "Horde", class = "Warlock" },
    ["Ormak Grimshot"] = { zone = "Orgrimmar", x = 66.20, y = 18.20, faction = "Horde", class = "Hunter" },
    ["Ormok"] = { zone = "Orgrimmar", x = 44.00, y = 54.40, faction = "Horde", class = "Rogue" },
    ["Pephredo"] = { zone = "Orgrimmar", x = 38.40, y = 85.60, faction = "Horde", class = "Mage" },
    ["Sagorne Creststrider"] = { zone = "Orgrimmar", x = 38.60, y = 36.20, faction = "Horde", class = "Shaman" },
    ["Shenthul"] = { zone = "Orgrimmar", x = 43.00, y = 53.40, faction = "Horde", class = "Rogue" },
    ["Sian'dur"] = { zone = "Orgrimmar", x = 67.80, y = 17.80, faction = "Horde", class = "Hunter" },
    ["Sian'tsu"] = { zone = "Orgrimmar", x = 37.80, y = 36.60, faction = "Horde", class = "Shaman" },
    ["Sorek"] = { zone = "Orgrimmar", x = 80.20, y = 32.40, faction = "Horde", class = "Warrior" },
    ["Thuul"] = { zone = "Orgrimmar", x = 38.60, y = 85.60, faction = "Horde", class = "Mage" },
    ["Ur'kyo"] = { zone = "Orgrimmar", x = 35.60, y = 87.60, faction = "Horde", class = "Priest" },
    ["Uthel'nay"] = { zone = "Orgrimmar", x = 39.00, y = 86.00, faction = "Horde", class = "Mage" },
    ["X'yera"] = { zone = "Orgrimmar", x = 35.80, y = 87.60, faction = "Horde", class = "Priest" },
    ["Xor'juul"] = { zone = "Orgrimmar", x = 67.00, y = 20.00, faction = "Horde", class = "Hunter" },
    ["Zayus"] = { zone = "Orgrimmar", x = 35.60, y = 87.20, faction = "Horde", class = "Priest" },
    ["Zel'mak"] = { zone = "Orgrimmar", x = 80.20, y = 29.60, faction = "Horde", class = "Warrior" },
    ["Zevrost"] = { zone = "Orgrimmar", x = 48.40, y = 45.60, faction = "Horde", class = "Warlock" },
    ["Kragg"] = { zone = "Stranglethorn Vale", x = 31.20, y = 28.60, faction = "Horde", class = "Hunter" },
    ["Haromm"] = { zone = "Swamp of Sorrows", x = 48.00, y = 57.80, faction = "Horde", class = "Shaman" },
    ["Kartosh"] = { zone = "Swamp of Sorrows", x = 48.40, y = 55.40, faction = "Horde", class = "Warlock" },
    ["Malosh"] = { zone = "Swamp of Sorrows", x = 44.80, y = 57.40, faction = "Horde", class = "Warrior" },
    ["Ogromm"] = { zone = "Swamp of Sorrows", x = 47.20, y = 53.20, faction = "Horde", class = "Hunter" },
    ["Archmage Shymm"] = { zone = "Thunder Bluff", x = 22.60, y = 14.80, faction = "Horde", class = "Mage" },
    ["Beram Skychaser"] = { zone = "Thunder Bluff", x = 22.20, y = 19.00, faction = "Horde", class = "Shaman" },
    ["Birgitte Cranston"] = { zone = "Thunder Bluff", x = 22.20, y = 17.20, faction = "Horde", class = "Mage" },
    ["Father Cobb"] = { zone = "Thunder Bluff", x = 25.40, y = 20.80, faction = "Horde", class = "Priest" },
    ["Holt Thunderhorn"] = { zone = "Thunder Bluff", x = 57.40, y = 89.40, faction = "Horde", class = "Hunter" },
    ["Kary Thunderhorn"] = { zone = "Thunder Bluff", x = 58.20, y = 87.80, faction = "Horde", class = "Hunter" },
    ["Ker Ragetotem"] = { zone = "Thunder Bluff", x = 57.80, y = 85.60, faction = "Horde", class = "Warrior" },
    ["Kym Wildmane"] = { zone = "Thunder Bluff", x = 76.80, y = 29.80, faction = "Horde", class = "Druid" },
    ["Malakai Cross"] = { zone = "Thunder Bluff", x = 24.80, y = 22.60, faction = "Horde", class = "Priest" },
    ["Miles Welsh"] = { zone = "Thunder Bluff", x = 25.40, y = 15.00, faction = "Horde", class = "Priest" },
    ["Sark Ragetotem"] = { zone = "Thunder Bluff", x = 57.20, y = 89.00, faction = "Horde", class = "Warrior" },
    ["Sheal Runetotem"] = { zone = "Thunder Bluff", x = 77.00, y = 27.40, faction = "Horde", class = "Druid" },
    ["Siln Skychaser"] = { zone = "Thunder Bluff", x = 23.00, y = 20.80, faction = "Horde", class = "Shaman" },
    ["Thurston Xane"] = { zone = "Thunder Bluff", x = 25.00, y = 20.60, faction = "Horde", class = "Mage" },
    ["Tigor Skychaser"] = { zone = "Thunder Bluff", x = 23.40, y = 19.20, faction = "Horde", class = "Shaman" },
    ["Torm Ragetotem"] = { zone = "Thunder Bluff", x = 57.40, y = 87.20, faction = "Horde", class = "Warrior" },
    ["Turak Runetotem"] = { zone = "Thunder Bluff", x = 76.40, y = 27.60, faction = "Horde", class = "Druid" },
    ["Urek Thunderhorn"] = { zone = "Thunder Bluff", x = 58.80, y = 86.60, faction = "Horde", class = "Hunter" },
    ["Ursyn Ghull"] = { zone = "Thunder Bluff", x = 25.40, y = 14.40, faction = "Horde", class = "Mage" },
    ["Austil de Mon"] = { zone = "Tirisfal Glades", x = 61.80, y = 52.45, faction = "Horde", class = "Warrior" },
    ["Cain Firesong"] = { zone = "Tirisfal Glades", x = 61.80, y = 52.40, faction = "Horde", class = "Mage" },
    ["Dannal Stern"] = { zone = "Tirisfal Glades", x = 32.60, y = 65.60, faction = "Horde", class = "Warrior" },
    ["Dark Cleric Beryl"] = { zone = "Tirisfal Glades", x = 61.60, y = 52.20, faction = "Horde", class = "Priest" },
    ["Dark Cleric Duesten"] = { zone = "Tirisfal Glades", x = 31.00, y = 66.00, faction = "Horde", class = "Priest" },
    ["David Trias"] = { zone = "Tirisfal Glades", x = 32.40, y = 65.65, faction = "Horde", class = "Rogue" },
    ["Gina Lang"] = { zone = "Tirisfal Glades", x = 61.60, y = 52.60, faction = "Horde", class = "Warlock" },
    ["Isabella"] = { zone = "Tirisfal Glades", x = 30.80, y = 66.00, faction = "Horde", class = "Mage" },
    ["Kayla Smithe"] = { zone = "Tirisfal Glades", x = 30.80, y = 66.40, faction = "Horde", class = "Warlock" },
    ["Marion Call"] = { zone = "Tirisfal Glades", x = 61.60, y = 52.05, faction = "Horde", class = "Rogue" },
    ["Maximillion"] = { zone = "Tirisfal Glades", x = 30.80, y = 66.20, faction = "Horde", class = "Warlock" },
    ["Rupert Boch"] = { zone = "Tirisfal Glades", x = 61.60, y = 52.40, faction = "Horde", class = "Warlock" },
    ["Aelthalyste"] = { zone = "Undercity", x = 49.20, y = 18.20, faction = "Horde", class = "Priest" },
    ["Anastasia Hartwell"] = { zone = "Undercity", x = 85.00, y = 10.20, faction = "Horde", class = "Mage" },
    ["Angela Curthas"] = { zone = "Undercity", x = 48.20, y = 15.60, faction = "Horde", class = "Warrior" },
    ["Baltus Fowler"] = { zone = "Undercity", x = 47.20, y = 17.00, faction = "Horde", class = "Warrior" },
    ["Carolyn Ward"] = { zone = "Undercity", x = 83.80, y = 71.60, faction = "Horde", class = "Rogue" },
    ["Christoph Walker"] = { zone = "Undercity", x = 47.20, y = 15.00, faction = "Horde", class = "Warrior" },
    ["Father Lankester"] = { zone = "Undercity", x = 49.60, y = 15.60, faction = "Horde", class = "Priest" },
    ["Father Lazarus"] = { zone = "Undercity", x = 47.40, y = 19.20, faction = "Horde", class = "Priest" },
    ["Gregory Charles"] = { zone = "Undercity", x = 84.60, y = 73.20, faction = "Horde", class = "Rogue" },
    ["Kaal Soulreaper"] = { zone = "Undercity", x = 86.00, y = 15.60, faction = "Horde", class = "Warlock" },
    ["Kaelystia Hatebringer"] = { zone = "Undercity", x = 85.20, y = 14.20, faction = "Horde", class = "Mage" },
    ["Lexington Mortaim"] = { zone = "Undercity", x = 84.20, y = 16.00, faction = "Horde", class = "Mage" },
    ["Luther Pickman"] = { zone = "Undercity", x = 86.20, y = 15.40, faction = "Horde", class = "Warlock" },
    ["Martha Strain"] = { zone = "Undercity", x = 85.80, y = 15.80, faction = "Horde", class = "Warlock" },
    ["Miles Dexter"] = { zone = "Undercity", x = 85.00, y = 71.20, faction = "Horde", class = "Rogue" },
    ["Pierce Shackleton"] = { zone = "Undercity", x = 85.40, y = 13.80, faction = "Horde", class = "Mage" },
    ["Richard Kerwin"] = { zone = "Undercity", x = 88.60, y = 16.00, faction = "Horde", class = "Warlock" },

    ["Fahrad"] = { zone = "Alterac Mountains", x = 84.40, y = 80.20, faction = "Neutral", class = "Rogue" },
    ["Alenndaar Lapidaar"] = { zone = "Ashenvale", x = 18.00, y = 59.80, faction = "Neutral", class = "Hunter" },
    ["Loganaar"] = { zone = "Moonglade", x = 52.40, y = 40.40, faction = "Neutral", class = "Druid" },
    ["Ian Strom"] = { zone = "Stranglethorn Vale", x = 26.80, y = 77.20, faction = "Neutral", class = "Rogue" },

}

function WL.IsClassTrainer(npcName)
    if not npcName then return false end
    return WL.ClassTrainers[npcName] ~= nil
end

function WL.GetClassTrainerInfo(npcName)
    return WL.ClassTrainers[npcName]
end

function WL.GetFactionClassTrainers()
    local faction = UnitFactionGroup("player")
    local list = {}
    for name, info in pairs(WL.ClassTrainers) do
        if info.faction == faction or info.faction == "Neutral" then
            list[name] = info
        end
    end
    return list
end
